version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalogapi:
    image: eventbrite/eventcatalogapi
    build:
      context: .\EventCatalogAPI/
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventCatalogDB;User Id=sa;Password=ProductApi(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      ExternalBaseUrl: http://localhost:7001
    ports:
      - "7001:80"
    container_name: eventbriteeventcatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  tokenserver:
    image: eventbrite/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:7502
    ports:
      - "7650:80"
    container_name: eventbritetokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver

  cart:
    image: eventbrite/cartapi
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    environment:
      IdentityUrl: http://172.23.192.1:7650
      ConnectionString: basket.data
    ports:
      - "7009:80"
    container_name: eventscartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basket.data

  WebMvc:
    image: eventbrite/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventCatalogUrl: http://eventcatalogapi
      IdentityUrl: http://172.23.192.1:7650
      CallBackUrl: http://localhost:7502
      CartUrl: http://cart
    ports:
      - "7502:80"
    container_name: eventwebshop
    networks:
      - frontend
    depends_on:
      - eventcatalogapi
      - tokensqlserver
      - cart


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi(!)
    ports:
      - "1498:1433"
    container_name: eventbritesqlserver
    networks:
      - backend

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
      SA_PASSWORD: ProductApi123(!)
    ports:
      - "1428:1433"
    container_name: eventstokensqlserver
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "7050:6379"
    container_name: basketdata
    networks:
      - backend